# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockman < Formula
  desc "Docker Compose manager with presets and shortcuts"
  homepage "https://github.com/catstackdev/dockman"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/catstackdev/dockman/releases/download/v0.1.1/dockman_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "6628c2b56a3ed365aa2f87c51e55419cb84b4f66311c905833dfdaa39fe7733d"

      def install
        bin.install "dockman"

        # Install shell completions (if available)
        if (bash_completion/"dockman.bash").exist?
          bash_completion.install "completions/dockman.bash" => "dockman"
        end
        if (zsh_completion/"_dockman").exist?
          zsh_completion.install "completions/_dockman" => "_dockman"
        end
        if (fish_completion/"dockman.fish").exist?
          fish_completion.install "completions/dockman.fish"
        end
      end
    end
    on_arm do
      url "https://github.com/catstackdev/dockman/releases/download/v0.1.1/dockman_0.1.1_Darwin_arm64.tar.gz"
      sha256 "e5dd0c36411d25582122447662727449ae865c0203db934953220ed34980c7e0"

      def install
        bin.install "dockman"

        # Install shell completions (if available)
        if (bash_completion/"dockman.bash").exist?
          bash_completion.install "completions/dockman.bash" => "dockman"
        end
        if (zsh_completion/"_dockman").exist?
          zsh_completion.install "completions/_dockman" => "_dockman"
        end
        if (fish_completion/"dockman.fish").exist?
          fish_completion.install "completions/dockman.fish"
        end
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/catstackdev/dockman/releases/download/v0.1.1/dockman_0.1.1_Linux_x86_64.tar.gz"
        sha256 "49f3d9ba27b049edbaeef3958bf4a45849b16ae0641d3604e2dfdecd2c7993dc"

        def install
          bin.install "dockman"

          # Install shell completions (if available)
          if (bash_completion/"dockman.bash").exist?
            bash_completion.install "completions/dockman.bash" => "dockman"
          end
          if (zsh_completion/"_dockman").exist?
            zsh_completion.install "completions/_dockman" => "_dockman"
          end
          if (fish_completion/"dockman.fish").exist?
            fish_completion.install "completions/dockman.fish"
          end
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/catstackdev/dockman/releases/download/v0.1.1/dockman_0.1.1_Linux_arm64.tar.gz"
        sha256 "89dc22bf4d3861710dd8400d3022927018fa575f2ecaee44296ab99767593d1c"

        def install
          bin.install "dockman"

          # Install shell completions (if available)
          if (bash_completion/"dockman.bash").exist?
            bash_completion.install "completions/dockman.bash" => "dockman"
          end
          if (zsh_completion/"_dockman").exist?
            zsh_completion.install "completions/_dockman" => "_dockman"
          end
          if (fish_completion/"dockman.fish").exist?
            fish_completion.install "completions/dockman.fish"
          end
        end
      end
    end
  end

  test do
    system "#{bin}/dockman", "version"
  end
end
